# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 19:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_field', models.SlugField()),
                ('title', models.CharField(max_length=100)),
                ('tags', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 11, 11, 19, 39, 33, 980861))),
                ('updated', models.DateTimeField(default=datetime.datetime(2017, 11, 11, 19, 39, 33, 980886))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
